![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# NumPy exercises


In [127]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print("numpy version:", np.__version__)

numpy version: 1.24.4


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array Creation

---
create empty numpy array

In [128]:
# your code

In [129]:
np.array([])

array([], dtype=float64)

---
Given the X python list convert it to an Y numpy array. Then print it with its type.

In [130]:
X = [[11, 12, 13], [14, 15, 16]]  # given
print(X, type(X))  # given example

[[11, 12, 13], [14, 15, 16]] <class 'list'>


In [131]:
# your code

In [132]:
Y = np.array(X)
print(Y, type(Y))

[[11 12 13]
 [14 15 16]] <class 'numpy.ndarray'>


---
Given the X numpy array, make a copy and store it on Y. then print its id
- are they having id values?
- are they having identical id?

In [133]:
X = np.array([5, 2, 3], dtype=int)  # given
print(X, id(X))  # given example

[5 2 3] 140645424005264


In [134]:
# your code

In [135]:
Y = np.copy(X)
print(Y, id(Y))  # different id

[5 2 3] 140645424005840


---
Create a numpy array with `integers` from 1 to 10
- using range

In [136]:
# your code

In [137]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

---
Create a numpy array with `integers` from 1 to 10
- using linspace

In [138]:
# your code

In [139]:
np.linspace(1, 10, 10, dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

---
Create a numpy array with the `odd integers` between 1 to 10

In [140]:
# your code

In [141]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

---
Create a numpy array with `integers` from 10 to 1, in descending order.

In [142]:
# your code

In [143]:
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array Attributes Basic
please use given numpy array `arr` to solve all questions in this section - Array Attributes


In [144]:
# given arr
X = [[11, 12, 13], [14, 15, 16]]
arr = np.array(X)
arr

array([[11, 12, 13],
       [14, 15, 16]])

---
Given numpy array `arr`, show its
- 1. dimension - which should be 2
- 2. element counts - which should be 6
- 3. row count
- 4. column count
- 5. item size of its data type (it is integer, so it must show 8-bit)

In [145]:
# your code

In [146]:
print(arr.ndim)
print(arr.size)
print(arr.shape[0])
print(arr.shape[1])
print(arr.itemsize)

2
6
2
3
8


---
Given numpy array `arr` is currently 2 by 3. Let's reshape this to be 3 by 2
- do not save or overwrite onto original arr, just show the temp outcome

In [147]:
# your code

In [148]:
arr.reshape(3, 2)

array([[11, 12],
       [13, 14],
       [15, 16]])

---
Given numpy array `arr` is currently 2 by 3. Let's reshape this to be 6 by 1
- do not save or overwrite onto original arr, just show the temp outcome

In [149]:
# your code

In [150]:
arr.reshape(6, 1)

array([[11],
       [12],
       [13],
       [14],
       [15],
       [16]])

---
Given 1D numpy array X(with large size), Let's reshape this to be 2D array have 4 rows

In [151]:
X = np.arange(1, 234125)  # Given

In [152]:
# your code

In [153]:
X.reshape(4, -1)

array([[     1,      2,      3, ...,  58529,  58530,  58531],
       [ 58532,  58533,  58534, ..., 117060, 117061, 117062],
       [117063, 117064, 117065, ..., 175591, 175592, 175593],
       [175594, 175595, 175596, ..., 234122, 234123, 234124]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array Indexation


---
Given the 1D X numpy array, show it's first element

In [154]:
X = np.array(["A", "B", "C", "D", "E"])  # GIVEN

In [155]:
# your code

In [156]:
X[0]

'A'

---
Given the X numpy array, show it's last element

In [157]:
X = np.array(["A", "B", "C", "D", "E"])  # GIVEN

In [158]:
# your code

In [159]:
X[-1]

'E'

---
Given the X numpy array, show it's first three elements

In [160]:
X = np.array(["A", "B", "C", "D", "E"])  # GIVEN

In [161]:
# your code

In [162]:
X[:3]  # remember! elements start at zero index

array(['A', 'B', 'C'], dtype='<U1')

---
Given the X numpy array, show all middle elements

In [163]:
X = np.array(["A", "B", "C", "D", "E"])  # GIVEN

In [164]:
# your code

In [165]:
X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

---
Given the X numpy array, show the elements in reverse position

In [166]:
X = np.array(["A", "B", "C", "D", "E"])  # GIVEN

In [167]:
# your code

In [168]:
X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

---
Given the X numpy array, show the elements in an odd position

In [169]:
X = np.array(["A", "B", "C", "D", "E"])

In [170]:
# your code

In [171]:
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

---
Given the X numpy matrix, show the first row elements

In [172]:
# GIVEN
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [173]:
# your code

In [174]:
X[0]

array([1, 2, 3, 4])

---
Given the X numpy matrix, show the 2nd from last row elements

In [175]:
# GIVEN
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [176]:
# your code

In [177]:
X[-2]

array([ 9, 10, 11, 12])

---
Given the X numpy matrix, show the 3rd element on 2nd row

In [178]:
# GIVEN
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [179]:
# your code

In [180]:
X[1, 2]

7

chained expression and comma expression both work same here for this case (but NOT ALWAYS) another possible answer can be

```X[1][2]```

---
Given the X numpy matrix, show the middle row's middle elements

In [181]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])  # Given
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [182]:
# your code

In [183]:
X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

---
Answer yourself. Is chained indexing works here?

In [184]:
# your answer

```X[1:-1][1:-1] ????```

wrong! why chained expression won't result as same as comma expression?

In [185]:
X[1:-1][1:-1]

array([], shape=(0, 4), dtype=int64)

---
Given the X numpy matrix, show the first two elements on the first two rows

In [186]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [187]:
# your code

In [188]:
X[:2, :2]

array([[1, 2],
       [5, 6]])

---
Answer yourself. Is chained indexing works here?

- X[:2][:2] wrong!

---
Given the X numpy matrix, show the last two elements on the last two rows

In [189]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])  # Given
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [190]:
# your code

In [191]:
X[2:, 2:]

array([[11, 12],
       [15, 16]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array Manipulation


---
Convert the given integer list to float numpy array

In [192]:
X = [-5, -3, 0, 10, 40]  # given

In [193]:
# your code

In [194]:
Xfloat = np.array(X, dtype=float)
Xfloat

array([-5., -3.,  0., 10., 40.])

---
Convert the float numpy array you just made to integer numpy array

In [195]:
# your code

In [196]:
Xint = np.array(Xfloat, int)
Xint

array([-5, -3,  0, 10, 40])

---
Reverse the given numpy array (first element becomes last)

In [197]:
X = np.array([-5, -3, 0, 10, 40])
X

array([-5, -3,  0, 10, 40])

In [198]:
# your code

In [199]:
X[::-1]

array([40, 10,  0, -3, -5])

---
Order (sort) the given numpy array using basic python function

In [200]:
X = np.array([0, 10, -5, 40, -3])
X

array([ 0, 10, -5, 40, -3])

In [201]:
# your code

In [202]:
X.sort()
X

array([-5, -3,  0, 10, 40])

---
Order (sort) the given numpy array using numpy function

In [203]:
X = np.array([0, 10, -5, 40, -3])
X

array([ 0, 10, -5, 40, -3])

In [204]:
# your code

In [205]:
np.sort(X)

array([-5, -3,  0, 10, 40])

see any difference from `sort` and  `np.sort` ??

---
Given the X numpy array, set the fifth element equal to 39

In [206]:
X = np.zeros(10)  # given
X

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [207]:
# your code

In [208]:
X[4] = 39
X

array([ 0.,  0.,  0.,  0., 39.,  0.,  0.,  0.,  0.,  0.])

---
Given the X numpy array, change the 50 with a 40

In [209]:
X = np.array([10, 20, 30, 50])  # given
X

array([10, 20, 30, 50])

In [210]:
# your code

In [211]:
X[3] = 40
# X[X==50] = 40 another possible answer
X

array([10, 20, 30, 40])

---
Given the X numpy matrix, change the last row with all `1`

In [212]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [213]:
# your code

In [214]:
X[-1] = 1
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

---
Given the X numpy matrix, change the last item on the last row with `0`

In [215]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [216]:
# your code

In [217]:
X[3, 3] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

---
Given the X numpy matrix, add 5 to every element

In [218]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])  # Given
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [219]:
# your code

In [220]:
X = X + 5
X

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Boolean arrays _(also called masks)_


---
Given the X numpy array, make a mask showing negative elements
- just show boolean array

In [221]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])  # given
X

array([-1,  2,  0, -4,  5,  6,  0,  0, -9, 10])

In [222]:
# your code

In [223]:
mask = X < 0
mask

array([ True, False, False,  True, False, False, False, False,  True,
       False])

---
Given the X numpy array, get the negative elements
- you can utilize the mask you just made

In [224]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])  # given
X

array([-1,  2,  0, -4,  5,  6,  0,  0, -9, 10])

In [225]:
# your code

In [226]:
X[X < 0]

array([-1, -4, -9])

---
Given the X numpy array, get numbers higher than 5

In [227]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])  # Given
X

array([-1,  2,  0, -4,  5,  6,  0,  0, -9, 10])

In [228]:
# your code

In [229]:
mask = X > 5
X[mask]

array([ 6, 10])

---
Given the X numpy array, get numbers higher than the elements mean

In [230]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])  # Given
X

array([-1,  2,  0, -4,  5,  6,  0,  0, -9, 10])

In [231]:
# your code

In [232]:
mask = X > X.mean()
X[mask]

array([ 2,  5,  6, 10])

---
Given the X numpy array, get numbers equal to 2 or 10

In [233]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])  # Given
X

array([-1,  2,  0, -4,  5,  6,  0,  0, -9, 10])

In [234]:
# your code

In [235]:
mask = (X == 2) | (X == 10)
X[mask]

array([ 2, 10])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

---
Given the X numpy array, show the sum of its elements

In [236]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])  # given
X

array([3, 5, 6, 7, 2, 3, 4, 9, 4])

In [237]:
# your code

In [238]:
# two possible answer
print(np.sum(X))
print(X.sum())

43
43


---
Given the X numpy array, show the average value of its elements

In [239]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])  # given
X

array([3, 5, 6, 7, 2, 3, 4, 9, 4])

In [240]:
# your code

In [241]:
# two possible answer
print(np.mean(X))
print(X.mean())

4.777777777777778
4.777777777777778


---
Given the X numpy matrix, show the sum of its (within) columns (adding horizontaliy)

In [242]:
# Given
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [243]:
# your code

In [244]:
X.sum(axis=0)  # remember: axis=0 columns; axis=1 rows

array([28, 32, 36, 40])

---
Given the X numpy matrix, show the mean value of its rows

In [245]:
# Given
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [246]:
# your code

In [247]:
X.mean(axis=1)  # remember: axis=0 columns; axis=1 rows

array([ 2.5,  6.5, 10.5, 14.5])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## More Numpy Function(zeros, zeros_like, any, all etc)


### logic functions

---
Given the X numpy array, return True if none of its elements is zero

In [248]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
X

array([-1,  2,  0, -4,  5,  6,  0,  0, -9, 10])

In [249]:
# your code

In [250]:
X.all()

False

---
Given the X numpy array, return True if any of its elements is zero

In [251]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
X

array([-1,  2,  0, -4,  5,  6,  0,  0, -9, 10])

In [252]:
# your code

In [253]:
X.all()

False

### array creation

---
Create a numpy array of size 10, filled with zeros.

In [254]:
# your code

In [255]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

---
Create a numpy array with values ranging from 10 to 49

In [256]:
# your code

In [257]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

---
Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [258]:
# your code

In [259]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

---
Create a numpy matrix of 2*2 integers, filled with ones.

In [260]:
# your code

In [261]:
np.ones((2, 2), dtype=int)

array([[1, 1],
       [1, 1]])

---
Create a numpy matrix of 3*2 float numbers, filled with ones.

In [262]:
# your code

In [263]:
np.ones([3, 2], dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

---
Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [264]:
X = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)  # given

In [265]:
# your code

In [266]:
np.ones_like(X)

array([[1, 1, 1],
       [1, 1, 1]])

---
Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [267]:
X = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)  # given

In [268]:
# your code

In [269]:
np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

---
Create a numpy matrix of 4*4 integers, filled with fives.

In [270]:
# your code

In [271]:
np.ones([4, 4], dtype=int) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

### linear algebra

---
Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [272]:
# your code

In [273]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### random number

---
Create a numpy array, filled with 3 random integer values between 0 and 9.

In [274]:
# your code

In [275]:
np.random.randint(10, size=3)

array([7, 7, 3])

---
Create a 3\*3\*3 numpy matrix, filled with random float values.

In [276]:
# your code

In [277]:
np.random.randn(3, 3, 3)  #  0 to 1 floats

array([[[-0.3192286 ,  0.55685473,  0.29420017],
        [ 0.04753047,  0.24702823,  0.20977275],
        [ 1.14358058, -1.78105074,  0.49429465]],

       [[-1.32621743,  1.07568818, -0.08124918],
        [ 0.04674066,  0.04104152,  0.95654411],
        [-1.54344706,  1.00083234, -0.37058521]],

       [[ 0.56894053, -0.12929023, -1.2421542 ],
        [ 0.18207476,  0.20351412,  1.05218831],
        [-0.0488045 , -0.26306209, -0.48660161]]])

---
Show the memory size of the given Z numpy matrix `np.zeros((10,10))`

In [278]:
# your code

In [279]:
Z = np.zeros((10, 10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes
