# Discretization of Continuous Numerical Data

* Numerical data is divided into distinct intervals.
* Through discretization, numerical features can be converted into categorical data.
* `Discretization` refers to the process of transforming a continuous variable into a variable with two or more categories.

In [3]:
import numpy as np
import pandas as pd

In [ ]:
# given data
age = np.array([[6], [12], [20], [36], [65]])

### np.digitize()
A method for dividing numerical features based on multiple threshold values.
* The input value for the `bins` parameter represents the left boundary of each interval.
* The data is divided into 4 intervals: [~ 20), [20, 30), [30, 64), [64 ~).
* You can change this behavior by setting `right = True`.


In [7]:
np.digitize(age, bins=[20, 30, 64])

array([[0],
       [0],
       [1],
       [2],
       [3]])

In [32]:
np.digitize(age, bins=[20, 30, 64], right=True)

array([[0],
       [0],
       [0],
       [2],
       [3]])

## np.where()

Discretizing Continuous Variables using `np.where(condition, factor1, factor2, ...)`

Can be used to discretize continuous variables by applying conditions and assigning corresponding factors.

* `condition`: The condition to evaluate.
* `factor1`: The value to assign when the condition is true.
* `factor2`: The value to assign when the condition is false.


In [9]:
x = np.arange(100)
np.where(x >= x.mean(), "high", "low")

array(['low', 'low', 'low', 'low', 'low', 'low', 'low', 'low', 'low',
       'low', 'low', 'low', 'low', 'low', 'low', 'low', 'low', 'low',
       'low', 'low', 'low', 'low', 'low', 'low', 'low', 'low', 'low',
       'low', 'low', 'low', 'low', 'low', 'low', 'low', 'low', 'low',
       'low', 'low', 'low', 'low', 'low', 'low', 'low', 'low', 'low',
       'low', 'low', 'low', 'low', 'low', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high'], dtype='<U4')

## sklearn.preprocessing.Binarizer()

`sklearn.preprocessing.Binarizer()` is used to convert continuous variables into a binary variable with two values based on a specified threshold:

* If the value is equal to or less than the threshold, it is converted to '0'.
* If the value is greater than the threshold, it is converted to '1'.


In [10]:
from sklearn.preprocessing import Binarizer

In [11]:
# 20을 기준으로 데이터를 2개 범주로 나눈다.
binarizer = Binarizer(threshold=20)
binarizer.fit_transform(age)

array([[0],
       [0],
       [0],
       [1],
       [1]])

## sklearn.preprocessing.KBinsDiscretizer() - New in version 0.20.

This function divides continuous feature values into multiple intervals, and you can specify the number of intervals to divide into.

* `encode`:
    * The default value is 'onehot', which returns a sparse matrix with one-hot encoding.
    * 'onehot-dense' returns a dense array.
    * 'ordinal' returns sequential categorical values.
* `strategy`:
    * 'quantile': Ensures that each interval contains approximately the same number of data points.
    * 'uniform': Ensures that each interval has the same width.
* The values of the intervals can be checked using the `bin_edges_` attribute.


In [12]:
from sklearn.preprocessing import KBinsDiscretizer

In [14]:
kb = KBinsDiscretizer(4, encode="ordinal", strategy="quantile")

kb.fit_transform(age)

array([[0.],
       [1.],
       [2.],
       [3.],
       [3.]])

In [15]:
kb = KBinsDiscretizer(4, encode="onehot-dense", strategy="quantile")

kb.fit_transform(age)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]])

In [16]:
kb = KBinsDiscretizer(4, encode="onehot-dense", strategy="uniform")

kb.fit_transform(age)

/Users/I751244/Desktop/mytutoring/ds101_2024Oct/venv/lib/python3.8/site-packages/sklearn/preprocessing/_discretization.py:248: FutureWarning: In version 1.5 onwards, subsample=200_000 will be used by default. Set subsample explicitly to silence this warning in the mean time. Set subsample=None to disable subsampling explicitly.
  warnings.warn(


array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
# 구간의 값
kb.bin_edges_

array([array([ 6.  , 20.75, 35.5 , 50.25, 65.  ])], dtype=object)

### Recall Discretization of Continuous Numerical Data

* Numerical data is divided into distinct intervals.
* Through discretization, numerical features can be converted into categorical data.
* Discretization refers to the process of transforming a continuous variable into a variable with two or more categories.


## Binning

Binning allows converting numerical data into categorical data by categorizing the numeric values.

* `pd.cut()`: Divides the data into intervals by specifying the boundary values for the intervals.
* `pd.qcut()`: Divides the data into a specified number of intervals, ensuring each interval contains the same number of data points, without explicitly specifying the boundary values.


### pd.cut() - Equal-Length Buckets Categorization

* The `pd.cut()` function allows easy categorization by taking numerical data and the interval boundaries as arguments.
* The data segmented using `pd.cut()` is returned as a Series with a categorical data type.


The `ages` data is returned as a categorical Series with 4 intervals, created by dividing the data into 5 equal-length buckets.


In [19]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]

# 18 ~ 25 / 25 ~ 35 / 35 ~ 60 / 60 ~ 100 이렇게 총 4구간
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

By using `cats.codes`, you can see the integer index representing which interval each element of `ages` belongs to. 
For example, 20 belongs to the first interval (index 0), and 27 belongs to the second interval (index 1).


In [43]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

By using `cats.value_counts()`, you can check the count of elements in each interval.
The `value_counts()` function helps to determine how many elements belong to each category in a categorical Series.

In [20]:
cats.value_counts()

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

When calling `pd.cut()`, you can add the `labels = [list]` argument to specify custom category labels for each interval.

In [23]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

#### Dividing into a Number of Intervals using pd.cut()

Instead of providing the specific bin boundaries as the second argument, you can simply input the number of intervals (bins) you want to create. 
The function will automatically divide the data into equal intervals based on the minimum and maximum values of the data.


In [35]:
data = np.random.rand(20)
data

array([0.32835824, 0.86019171, 0.10191386, 0.1344057 , 0.43723183,
       0.82223831, 0.51914262, 0.09348704, 0.74471795, 0.64778606,
       0.35022784, 0.93907817, 0.26641927, 0.63923197, 0.36266927,
       0.2806426 , 0.23790338, 0.14698961, 0.38101232, 0.38174405])

In [36]:
# 20개의 data성분에 대해, 동일한 길이의 구간으로 4개를 나누었고,
# 기준은 소수2번째 자리까지를 기준으로 한다.
cat_data = pd.cut(data, 4, precision=2)
cat_data

[(0.3, 0.52], (0.73, 0.94], (0.093, 0.3], (0.093, 0.3], (0.3, 0.52], ..., (0.093, 0.3], (0.093, 0.3], (0.093, 0.3], (0.3, 0.52], (0.3, 0.52]]
Length: 20
Categories (4, interval[float64, right]): [(0.093, 0.3] < (0.3, 0.52] < (0.52, 0.73] < (0.73, 0.94]]

In [48]:
cat_data.value_counts()

(0.019, 0.23]    4
(0.23, 0.45]     3
(0.45, 0.66]     5
(0.66, 0.87]     8
Name: count, dtype: int64

### pd.qcut() - Equal-Size Buckets Categorization

Pandas provides a function called `qcut()`.

* It defines intervals based on the specified number of intervals (bins).
* Unlike `pd.cut()`, which divides the data based on the minimum and maximum values, 
* `pd.qcut()` takes the data distribution into account and divides the data into intervals such that each interval contains an equal number of data points, using quantiles as the bin boundaries.


In [37]:
data2 = np.random.randn(100)
data2

array([ 0.07118461,  0.58828603, -0.96025924,  0.87517975, -0.09614677,
        0.17123732, -1.48626959,  0.41262538,  0.35301297, -0.78063117,
        0.35072148,  0.87255648,  0.71211948,  1.02765571,  0.99446444,
        0.12897907,  0.13612712, -1.3425968 , -0.67756979,  0.00304775,
       -0.69362585, -1.86819305,  0.53666496,  0.30444107, -0.33238734,
        1.66121423, -0.53735448, -1.87131401,  1.30299552, -0.15427876,
       -2.33389574,  1.98737294,  2.35776796,  0.35582484,  1.31869654,
       -0.2154436 ,  0.12625805, -1.51001384,  0.61742952, -0.99503719,
        1.09695797, -1.62466504, -0.18892507,  1.31007985, -1.77784934,
       -0.23150922, -0.23205505,  1.16461925, -1.30633808, -2.37100002,
        0.16965368, -0.27289183,  0.10062823, -0.05160269, -0.12395643,
        0.02203619,  0.05755136, -0.16712343,  0.08087776, -0.5172681 ,
        0.03539893, -1.16707262,  1.27474388, -0.36207931, -0.86235248,
       -1.15897949,  1.24484957, -0.1294599 ,  0.23731136, -1.56

In [38]:
cats = pd.qcut(data2, 4)
cats

[(0.0156, 0.509], (0.509, 2.358], (-2.372, -0.716], (0.509, 2.358], (-0.716, 0.0156], ..., (-0.716, 0.0156], (0.509, 2.358], (-2.372, -0.716], (0.0156, 0.509], (-0.716, 0.0156]]
Length: 100
Categories (4, interval[float64, right]): [(-2.372, -0.716] < (-0.716, 0.0156] < (0.0156, 0.509] < (0.509, 2.358]]

* `cats = pd.qcut(data2, 4)` divides the data into 4 intervals.
* Instead of simply dividing the range between the minimum and maximum values into four equal parts, it considers the distribution and splits the data into quartiles.
* Unlike the `cut()` function, it cannot be said that each interval has the same length.


In [52]:
cats.value_counts()

(-2.5229999999999997, -0.726]    25
(-0.726, -0.188]                 25
(-0.188, 0.707]                  25
(0.707, 2.679]                   25
Name: count, dtype: int64

# Wine Example

### 1. Discretize (Discretization)

**Objective**: Convert continuous data into categorical data. For example, discretize the `alcohol` or `flavanoids` feature in the wine dataset into different categories.

**Example**: Discretize the `alcohol` feature in the wine dataset into 3 categories.

```python
from sklearn.datasets import load_wine
import pandas as pd

# Load the wine dataset
wine = load_wine()
X = pd.DataFrame(wine.data, columns=wine.feature_names)

# Discretize the 'alcohol' feature into 3 categories
alcohol_bins = [0, 11, 12, 14]
alcohol_labels = ['Low', 'Medium', 'High']
X['alcohol_discretized'] = pd.cut(X['alcohol'], bins=alcohol_bins, labels=alcohol_labels)

# Show the discretized 'alcohol' column
print(X[['alcohol', 'alcohol_discretized']].head())


In [52]:
from sklearn.datasets import load_wine

wine = load_wine()

df = pd.DataFrame(wine.data, columns=wine.feature_names)
df

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 13 columns]

In [67]:
cats = pd.cut(
    df["alcohol"],
    bins=[11, 12, 13, 15, 19],
    labels=["Low", "Medium", "High", "VeryHigh"],
)
print(cats.value_counts())
df["alcohol_discretized"] = cats
df

alcohol
High        92
Medium      64
Low         22
VeryHigh     0
Name: count, dtype: int64


alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline alcohol_discretized  
0                            3.92   1065.0                High  
1                            3.40   1050.0                High  
2                            3.17   1185.0                High  
3                            3.45   1480.0                High  
4                            2.93    735.0                High  
..                            ...      ...                 ...  
173                          1.74    740.0                High  
174                          1.56    750.0                High  
175                          1.56    835.0                High  
176                          1.62    840.0                High  
177                          1.60    560.0                High  

[178 rows x 14 columns]

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline alcohol_discretized  
0                            3.92   1065.0                High  
1                            3.40   1050.0                High  
2                            3.17   1185.0                High  
3                            3.45   1480.0                High  
4                            2.93    735.0                High  
..                            ...      ...                 ...  
173                          1.74    740.0                High  
174                          1.56    750.0                High  
175                          1.56    835.0                High  
176                          1.62    840.0                High  
177                          1.60    560.0                High  

[178 rows x 14 columns]

## Problem Questions:
The alcohol feature is divided into 3 categories: Low, Medium, and High. Check which category each wine belongs to.

Divide the alcohol feature into 5 categories: Very Low, Low, Medium, High, and Very High, and check how many wines belong to each category.

Apply the same method to the flavanoids feature, discretizing it into Low, Medium, and High. Then, check the distribution of each category.