![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# NumPy exercises


In [110]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print("numpy version:", np.__version__)
# given python list:

numpy version: 1.24.4


In [3]:
# GIVEN INPUT
X1=[11,12,13,14]
X2=np.array(X1)
X3 = np.array([
    [11,   12,  13, 14],
    [15,   16,  17,  18],
    [19,  20, 21, 22],
    [23, 24, 25, 26]
])
X4=np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

Create a numpy array of size 10, filled with zeros.

In [4]:
#1 your code goes here
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create a numpy array with values ranging from 10 to 49

In [5]:
#2 your code goes here
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Create a numpy matrix of 2*2 integers, filled with ones.

In [6]:
#3 your code goes here
np.ones((2,2), dtype = int)

array([[1, 1],
       [1, 1]])

Create a numpy matrix of 3*2 float numbers, filled with ones.

In [7]:
#4 your code goes here
np.ones([3, 2], dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [23]:
X = np.arange(4, dtype=int) # given

#5 your code goes here
np.ones_like(X)

array([1, 1, 1, 1])

Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [24]:
X = np.array([[1, 2, 3], [4, 5, 6]], dtype=int) # given

#6 your code goes here
np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

Create a numpy matrix of 4*4 integers, filled with fives.

In [10]:
#7 your code goes here
np.ones([4, 4], dtype=int) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [26]:
X = np.array([[2, 3], [6, 2]], dtype=int) # given

#8 your code goes here

np.ones_like(X) * 7

array([[7, 7],
       [7, 7]])

Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [27]:
#9 your code goes here
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Create a numpy array, filled with 3 random integer values between 0 and 9.

In [28]:
#10 your code goes here
np.random.randint(10, size=3)

array([9, 3, 0])

Create a 3\*3\*3 numpy matrix, filled with random float values.

In [29]:
#11 your code goes here
ra = np.random.randn(3, 3, 3)  #  0 to 1 floats
ra

array([[[ 1.63621062, -0.41344517,  0.72342271],
        [-1.32120878, -0.27695407,  0.5223474 ],
        [ 0.47642552, -0.75829975,  0.46269849]],

       [[ 0.77949672, -0.90615572,  2.44000193],
        [ 0.93725019, -0.45303002, -0.89468711],
        [-0.43373423, -0.28982143, -0.10870316]],

       [[ 0.16394713,  1.42161311,  0.09356939],
        [-0.4295275 ,  1.18217193, -0.26703148],
        [-0.18573977, -1.52445907, -0.70218679]]])

In [30]:
# another possible answer
np.random.random((3,3,3)) 

array([[[6.98643034e-01, 9.29252223e-01, 6.77244664e-02],
        [5.04511710e-01, 9.57908119e-01, 1.82276898e-01],
        [7.92716288e-01, 5.37757193e-01, 4.62644803e-01]],

       [[6.77094391e-01, 9.20458603e-01, 6.46025517e-01],
        [4.62340167e-01, 2.28531856e-01, 3.39468753e-01],
        [8.48305796e-01, 1.75870829e-01, 5.23946146e-01]],

       [[2.32118049e-01, 4.86808366e-02, 3.67986772e-01],
        [9.54281771e-02, 3.87084365e-02, 1.07772511e-01],
        [3.61672768e-01, 1.33927324e-04, 5.77544435e-02]]])

Given the X python list convert it to an Y numpy array. Then print it with its type.

In [32]:
X = [11, 12, 13] # given
print(X, type(X))

#12 your code goes here
# create Y then do `print(Y, type(Y))`
Y = np.array(X)
print(Y, type(Y))

[11, 12, 13] <class 'list'>
[11 12 13] <class 'numpy.ndarray'>


Given the X numpy array, make a copy and store it on Y.

In [35]:
X = np.array([5, 2, 3], dtype=int) # given
print(X, id(X))

# 13 your code goes here
# create Y then do `print(Y, id(Y))`

Y = np.copy(X)
print(Y, id(Y))  # different id

[5 2 3] 140603013379056
[5 2 3] 140602744746992


Create a numpy array with numbers from 1 to 10

In [36]:
#14 your code goes here
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Create a numpy array with the odd numbers between 1 to 10

In [37]:
#15 your code goes here
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

Create a numpy array with numbers from 1 to 10, in descending order.

In [38]:
#16 your code goes here
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [39]:
#17 your code goes here
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Show the memory size of the given Z numpy matrix np.zeros((10,10))

In [42]:
Z = np.zeros((10, 10)) # given

#18 your code goes here
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array indexation


Given the 1D X numpy array, show it's first element

In [43]:
X = np.array(['A', 'B', 'C', 'D', 'E']) # GIVEN
#19 your code goes here
X[0]

'A'

Given the X numpy array, show it's last element

In [44]:
X = np.array(['A', 'B', 'C', 'D', 'E'])  # GIVEN
# 20 your code goes here
X[-1]

'E'

Given the X numpy array, show it's first three elements

In [45]:
X = np.array(['A', 'B', 'C', 'D', 'E']) # GIVEN

#21 your code goes here
X[0:3]  # remember! elements start at zero index

array(['A', 'B', 'C'], dtype='<U1')

Given the X numpy array, show all middle elements

In [47]:
X = np.array(['A', 'B', 'C', 'D', 'E']) #GIVEN

#22 your code goes here
X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

Given the X numpy array, show the elements in reverse position

In [51]:
X = np.array(['A', 'B', 'C', 'D', 'E'])

#23 your code goes here
X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

Given the X numpy array, show the elements in an odd position

In [50]:
X = np.array(['A', 'B', 'C', 'D', 'E'])

#24 your code goes here
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

Given the X numpy matrix, show the first row elements

In [53]:
# GIVEN
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#25 your code goes here
X[0]

array([1, 2, 3, 4])

Given the X numpy matrix, show the 2nd from last row elements

In [54]:
# GIVEN
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# 26 your code goes here
X[-2]

array([ 9, 10, 11, 12])

Given the X numpy matrix, show the 3rd element on 2nd row

In [57]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])


# 27 your code goes here
X[1, 2]

7

chained expression and comma expression both work same here for this case (but NOT ALWAYS) another possible answer can be

```X[1][2]```

---
#28 Given the X numpy matrix, show the middle row's middle elements

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# your code goes here
X[1:-1, 1:-1]

```X[1:-1][1:-1] ????```

wrong! why chained expression won't result as same as comma expression?

In [ ]:
X[1:-1][1:-1]

array([], shape=(0, 4), dtype=int32)

---
#29 Given the X numpy matrix, show the first two elements on the first two rows

In [60]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# 29 your code goes here
X[:2, :2]

array([[1, 2],
       [5, 6]])

In [61]:
# X[:2][:2] wrong!
X[0:2, 0:2]

array([[1, 2],
       [5, 6]])

---
#30 Given the X numpy matrix, show the last two elements on the last two rows

In [63]:

# given
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# 30 your code goes here

X[2:, 2:]

array([[11, 12],
       [15, 16]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array manipulation


---
#31 Convert the given integer numpy array to float

In [64]:
X = [-5, -3, 0, 10, 40] # given

# your code:
Xfloat = np.array(X, float)
Xfloat

array([-5., -3.,  0., 10., 40.])

---
#32 Convert the float numpy array you just made to integer numpy array

In [65]:
# your code:
Xint=np.array(Xfloat, int)
Xint

array([-5, -3,  0, 10, 40])

---
#33 Reverse the given numpy array (first element becomes last)

In [ ]:

X = [-5, -3, 0, 10, 40] # your code

#33 your code goes here
X[::-1]

---
#34 Order (sort) the given numpy array using basic python function

In [74]:
X = [0, 10, -5, 40, -3]

# 34 your code goes here
X.sort()
X

[-5, -3, 0, 10, 40]

---
#35 Order (sort) the given numpy array using numpy function

In [75]:
X = [0, 10, -5, 40, -3]

# 34 your code goes here
np.sort(X)

array([-5, -3,  0, 10, 40])

see any difference from `sort` and  `np.sort` ??

---
#35 Given the X numpy array, set the fifth element equal to 39

In [77]:
X = np.zeros(10) # given

#35 your code goes here
X[4] = 39
X

array([ 0.,  0.,  0.,  0., 39.,  0.,  0.,  0.,  0.,  0.])

---
#36 Given the X numpy array, change the 50 with a 40

In [78]:
X = np.array([10, 20, 30, 50])

#36 your code goes here
X[3] = 40
X

array([10, 20, 30, 40])

---
Given the X numpy matrix, change the last row with all 1

In [80]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# 37 your code goes here
X[-1] = 1
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

---
#38 Given the X numpy matrix, change the last item on the last row with a 0

In [81]:

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# 38 your code goes here
X[-1, -1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

---
#39 Given the X numpy matrix, add 5 to every element

In [82]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# 39 your code goes here
X + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Boolean arrays _(also called masks)_


---
#40 Given the X numpy array, make a mask showing negative elements

In [86]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])  # given

# 40 your code goes here
mask = X < 0
mask

array([ True, False, False,  True, False, False, False, False,  True,
       False])

---
#41 Given the X numpy array, get the negative elements (you can utilize the mask you just made)

In [87]:
#41 your code goes here
X[mask]

array([-1, -4, -9])

---
#42 Given the X numpy array, get numbers higher than 5

In [88]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

#42 your code goes here
mask = X > 5
X[mask]

array([ 6, 10])

---
#43 Given the X numpy array, get numbers higher than the elements mean

In [89]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

# your code
mask = X > X.mean()
X[mask]

array([ 2,  5,  6, 10])

---
#44 Given the X numpy array, get numbers equal to 2 or 10

In [90]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

# 44 your code goes here
mask = (X == 2) | (X == 10)
X[mask]

array([ 2, 10])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic functions


---
#45 Given the X numpy array, return True if none of its elements is zero

In [91]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

#45 your code goes here

X.all()

False

---
#46 Given the X numpy array, return True if any of its elements is zero

In [92]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

#46 your code goes here

X.any()

True

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

---
#47 Given the X numpy array, show the sum of its elements

In [98]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4]) # given

# 47 your code goes here
np.sum(X)

43

In [99]:
# also this works!
X.sum()

43

---
#48 Given the X numpy array, show the mean value of its elements

In [101]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])  # given

# 48 your code goes here
np.mean(X)

4.777777777777778

In [100]:
# also this works!
X.mean()

4.777777777777778

---
#49 Given the X numpy matrix, show the sum of its (within) columns (adding horizontaliy)

In [102]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# 49 your code goes here
X.sum(axis=0) # remember: axis=0 columns; axis=1 rows

array([28, 32, 36, 40])

---
#50 Given the X numpy matrix, show the mean value of its rows

In [104]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# 50 your code goes here
X.mean(axis=1)  # remember: axis=0 columns; axis=1 rows

array([ 2.5,  6.5, 10.5, 14.5])

---
Given the X numpy array, show the max value of its elements

In [106]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

# 51 your code goes here
np.max(X)

10

In [107]:
# also this works
X.max()

10

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

# End of this page