# if

In [1]:
score = 34

if score >= 90:
    print("A")
elif score >= 80:
    print("B")
elif score >= 70:
    print("C")
elif score >= 60:
    print("D")
else:
    print("F")

F


In [2]:
def showGrade(x):
    if x >= 90:
        print("A")
    elif x >= 80:
        print("B")
    elif x >= 70:
        print("C")
    elif x >= 60:
        print("D")
    else:
        print("F")


showGrade(35)

F


In [3]:
def getGrade(x):
    if x >= 90:
        return "A"
    elif x >= 80:
        return "B"
    elif x >= 70:
        return "C"
    elif x >= 60:
        return "D"
    else:
        return "F"


"I got " + getGrade(35)

'I got F'

In [4]:
scores = [84, 100, 90, 95, 70, 69, 67, 91]

for score in scores:
    print(getGrade(score), end=", ")

B, A, A, A, C, D, D, A, 

In [5]:
h, m = input().split()
h = int(h)
m = int(m)

if m >= 45:
    print(h, m - 45)

ValueError: not enough values to unpack (expected 2, got 1)

# LIST

In [ ]:
a, b = input().split()
a = int(a)
b = int(b)

lst = input().split()

for i in range(a):
    c = lst[i]
    if int(c) < b:
        print(c, end=" ")

1 4 2 3 

In [ ]:
N, M = input().split()
N = int(N)  # number of bucket
M = int(M)  # number of changes

lst = [0] * N
for i in range(M):
    a, b, c = input().split()
    a = int(a)
    b = int(b)
    c = int(c)
    lst[a - 1 : b] = [c] * (b - a + 1)  # range index

print(lst)

[1, 2, 1, 1, 0]


In [ ]:
N, M = map(int, input().split())

lst = [0] * N
for i in range(M):
    a, b, c = map(int, input().split())
    lst[a - 1 : b] = [c] * (b - a + 1)  # range index
    # lst[a - 1:b] = c ERROR

print(lst)

[1, 2, 1, 1, 0]


# numpy array

In [6]:
import numpy as np

In [9]:
lst = [11, 12, 13, 14]
print(lst)
lst

[11, 12, 13, 14]


[11, 12, 13, 14]

In [10]:
arr = np.array([11, 12, 13, 14])
print(arr)
arr

[11 12 13 14]


array([11, 12, 13, 14])

In [11]:
lst[1] = lst[1] * 2
lst[2] = lst[2] * 2
lst

[11, 24, 26, 14]

In [12]:
arr[1] = arr[1] * 2
arr[2] = arr[2] * 2
arr

array([11, 24, 26, 14])

In [19]:
arr2 = np.array([15, 16, 17, 18, 19])
arr2[-3:] = 99  # broadcasting
arr2

array([15, 16, 99, 99, 99])